### ISSUE TITLE
Add ci and license check for safe.

### ISSUE THREAD

**Issue by wu-sheng** [SkywalkingTest/skywalking-agent-testcases#11]
cc @peng-yongsheng @lytscu @ascrutae

**Comment by kezhenxu94** [comment]
@wu-sheng as far as I know, there is a maven plugin [RAT](http://creadur.apache.org/rat/apache-rat-plugin/) that does the license check, maybe it can do this task

**Comment by wu-sheng** [comment]
I have forgotten about this :) But I think we should do this. Right now, CI is not working very well, and lack real check.

**Comment by wu-sheng** [comment]
This repo is closing, and moving into Apache repo.
