### ISSUE TITLE
if the server whitch run testcases is not very strong and use default settings the most testcases will fail 

### ISSUE THREAD

**Issue by dsc6636926** [SkywalkingTest/skywalking-agent-testcases#53]
i think the default settings witch run 8 cases paralleled without set --parallel_running_case_number , container will not work well on the limited mermery resource

**Comment by wu-sheng** [comment]
The default setting is based on our test vm.

**Comment by dsc6636926** [comment]
i just want help somebody else who write correct code but run testcases failed ~

**Comment by wu-sheng** [comment]
Yes. Do you have any thoughts to improve this repo? I am glad to hear.

**Comment by dsc6636926** [comment]
for short term i think we can update doc to tell developer the parameter --parallel_running_case_number, 
for long term,i think the default parallel_running_case_number can be dynamically by cpu num and free memery size

**Comment by wu-sheng** [comment]
Make sense. Please do.
