### ISSUE TITLE
yaml.parser.ParserError

### ISSUE THREAD

**Issue by BFergerson** [SkywalkingTest/skywalking-agent-testcases#54]
Not sure what I'm doing wrong here. I've tried it on multiple scenarios and I get the same result.

```bash
git clone https://github.com/SkyAPMTest/agent-auto-integration-testcases
cd agent-auto-integration-testcases/spring-scenario
mvn package docker:build
```
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] skywalking-spring-scenrio .......................... SUCCESS [  0.410 s]
[INFO] spring-projectA .................................... SUCCESS [  2.680 s]
[INFO] spring-projectB .................................... SUCCESS [  1.074 s]
[INFO] spring-projectC .................................... SUCCESS [  0.725 s]
[INFO] spring-projectD .................................... SUCCESS [  0.939 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.011 s
[INFO] Finished at: 2019-03-10T19:36:25-06:00
[INFO] Final Memory: 51M/1035M
[INFO] ------------------------------------------------------------------------
```

```bash
cd config
docker-compose up
```
```
ERROR: yaml.parser.ParserError: while parsing a block collection
  in "./docker-compose.yml", line 20, column 6
expected <block end>, but found '<scalar>'
  in "./docker-compose.yml", line 20, column 25
```

I've tried formatting the file and it gives the same error with different offsets.

Docker compose version: 1.23.2
OS: Ubuntu 18.04

**Comment by wu-sheng** [comment]
@ascrutae could you guide here?

**Comment by ascrutae** [comment]
Could you post me the docker-compose.yml?

**Comment by wu-sheng** [comment]
I think he is using your yaml in spring scenario

**Comment by BFergerson** [comment]
@ascrutae, yeah I'm using what's currently in the repo. Those commands are the only ones I need to run to make that error appear. You linked a guide I missed in another comment though so those might fix it.

**Comment by wu-sheng** [comment]
@BFergerson I think this document should help, https://github.com/SkyAPMTest/agent-auto-integration-testcases/blob/master/docs/how-to-write-a-plugin-testcase.md#run-test-cases . This repo is built for automatic tests in every night, to generate [this report](https://github.com/SkyAPMTest/agent-integration-test-report). 

Please try.

**Comment by BFergerson** [comment]
I was under the impression the above was how you ran a single scenario. I can see now the recommend way would be:
```bash
./deploy-test.sh -p spring-scenario
```
