### ISSUE TITLE
how to integreation testcases

### ISSUE THREAD

**Issue by dmsolr** [SkywalkingTest/skywalking-agent-testcases#67]
Hi all, 
I am trying to write an agent's auto-testcases. But something puzzle me for long time.
1. Can I run testcases without deploy-test.sh. That means I run the docker-compose.yml only. If I can, how to get the report.
2. to execute deploy-test.sh, it has to clone the Apache Skywalking's source everytime?
3. How to configure my agent's repo, which I push my testcases.

Thanks

**Comment by ascrutae** [comment]
> Can I run testcases without deploy-test.sh. That means I run the docker-compose.yml only. If I can, how to get the report.

I don't suggest to do this. because  you have to learn all the logic of process about `agent-auto-integration-testcases` repo

> to execute deploy-test.sh, it has to clone the Apache Skywalking's source everytime?

Try to run `./deploy-test.sh -h` command, and then you will find the answer
 
> How to configure my agent's repo, which I push my testcases.

Try to run `./deploy-test.sh -h` command, everything in the `./deploy-test.sh -h`. :-P

**Comment by dmsolr** [comment]
Thank you very much.
emmm, I have red the docs, and `./deploy-test.sh -h` has been try to run. But it is unbelievable that something likes the arguments cannot been recognized.
In another word, it dosen't show its usage when I run `./deploy-test.sh -h`.

It runs on Centos7
