### ISSUE TITLE
testcase.yml with testcase.desc

### ISSUE THREAD

**Issue by wayilau** [SkywalkingTest/skywalking-agent-testcases#69]
I was confused with testcase.yml with testcase.desc, i 've found that there is no testcase.desc file in any other scenario folder.  but when i run "./deploy-test.sh" , the log "
grep: /Users/francis/workspc/agent-auto-integration-testcases/testcases/hessian-scenario-4.0.38/testcase.desc: No such file or directory" tells me that i need a testcase.desc.

**Comment by ascrutae** [comment]
This is a strategy problem. the `testcase.desc` file is auto-generated by the test case platform. Could you show me more detail about this problem?

**Comment by wayilau** [comment]
i've finish build the agent.
![image](https://user-images.githubusercontent.com/3197838/57755839-75c6c680-7724-11e9-9b94-7bc1031cfc9f.png)

**Comment by wu-sheng** [comment]
This repo is closing, and moving into Apache repo.
